from os import getenv


API_ENABLE_HTTPS_REDIRECT: bool = False
API_ENABLE_CORS: bool = bool(getenv("API_ENABLE_CORS"))

API_SECRET: str = getenv("API_SECRET")
API_MINUTES_EXPIRE_TOKEN: int = int(getenv("API_MINUTES_EXPIRE_TOKEN", 30))

MIN_CONNECTIONS: int = getenv("MIN_CONNECTIONS")
MAX_CONNECTIONS: int = getenv("MAX_CONNECTIONS")

CONNECTION_STRING: str = getenv("CONNECTION_STRING")
CONNECTION_STRING_TEST: str = getenv("CONNECTION_STRING_TEST")
